### ISSUE TITLE
Higher Resolution

### ISSUE THREAD

**Issue by HMVocaloid** [blupi-games/planetblupi-dev#11]
This is kind of an odd question, but is it possible for Planet Blupi to run at a higher resolution? I changed one piece of code to make it the native res but the UI doesn't look right.
![image](https://user-images.githubusercontent.com/66088611/123334523-3d079700-d511-11eb-9fec-2c28c2119b27.png)

**Comment by Skywalker13** [comment]
Hi

I started the work some years ago but only for the assets https://github.com/blupi-games/planetblupi/issues/6
It's in stand-by...

Of course, you can hack the game but the maps are small and it will change the gameplay. I don't like that very much. I prefer my work on new high definition sprites instead of just see the whole map without scrolling.
